name: Publish NPM package and Create GitHub Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "apps/cli/package.json"

permissions:
  id-token: write
  contents: write

jobs:
  publish-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies and build
        run: |
          cd ./apps/cli
          pnpm i
          pnpm build

      - name: Publish to NPM
        run: npm publish
        working-directory: ./apps/cli

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./apps/cli

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.current-version}}
          release_name: Release v${{ steps.package-version.outputs.current-version }}
          body: |
            Release of version ${{ steps.package-version.outputs.current-version }}
          draft: false
          prerelease: false
